defaults:
  - dset: MedleyDB

MedleyDB:
  sample_rate: 44100

MUSDB18-HQ:
  sample_rate: 44100

DAFX:
  sample_rate: 36000

LibriSpeech:
  sample_rate: 16000

duration: 5

lr: 1e-4
lr_gamma: 0.98
batch_size: 8

early_stop: False
max_epoch: 200
patience: 30

MEE:
  channels: [ 16, 32, 64, 128, 256, 256, 512, 512, 1024, 1024, 2048, 2048 ]
  kernels: [ 25, 25, 15, 15, 10, 10, 10, 10, 5, 5, 5, 5 ]
  strides: [ 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1 ]
  dilation: [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
  z_dim: 1
  bias: True
  norm: 'batch'
  activation: "relu"