encoder: "MEE"

n_params: 6

sample_rate: 16000

duration: 5

loss_type: "params"  # or "mel"

mel_loss:
  fft_sizes: [256, 1024, 4096]
  hop_sizes: [64, 256, 1024]
  win_lengths: [256, 1024, 4096]

lr: 1e-4
lr_gamma: 0.98
batch_size: 8

early_stop: False
max_epoch: 200
min_epoch: 100
patience: 30

### for small datasets:
#compressors: "5profiles.pt"
#control_ranges: [[-38, 0], [0, 7.3], [0, 5], [0, 5], [0, 13], [0, 705]]

### for large datasets:
compressors: "30profiles.pt"
control_ranges: [[-60, 0], [0, 15], [0, 130], [0, 130], [0, 500], [0, 2000]]

TFE:
  f_dim: 64
  t_dim: 431

model_save: "pretrained_model/pretrained_MEE.pt"